export const GET_ALL_ABSENCES_REQUEST = 'GET_ALL_ABSENCES_REQUEST';
export const GET_ALL_ABSENCES_REQUEST_SUCCESS = 'GET_ALL_ABSENCES_REQUEST_SUCCESS';
export const GET_ALL_ABSENCES_REQUEST_FAILED = 'GET_ALL_ABSENCES_REQUEST_FAILED';